# Imports

In [20]:
from tools import load_dataset as ldts
from tools import feature_name_gen as fng
import tools.feature_extraction as fe
import pandas as pd
import numpy as np

## Load Images

In [21]:
dts_path = 'dataset_train/'

imgs, labels = ldts.load_dataset(dts_path)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'datasets_train/fake/'

### Create Dataframe

#### IMG
Img (784)

In [ ]:
# print(imgs[0])
S_images = []
for img in imgs:
    S_images.append(fe.feature_SerializedImg(img=img))

S_images = np.array(S_images)
print("Data shape: ",S_images.shape)

df = pd.DataFrame(S_images) # Images
df.columns = fng.gen_name("img", 784)
print("Dataframe shape: ", df.shape)


Data shape:  (30, 784)
Dataframe shape:  (30, 784)


## Extract New Features and add to Dataframe

#### Mean Color
Img (784) | Mean Color (1)

In [ ]:
cMean = []
for img in imgs:
    cMean.append(fe.feature_colorMean(img=img))

cMean = np.array(cMean)
print("Data shape: ", cMean.shape)

temp_df = pd.DataFrame(cMean)
temp_df.columns = ["MeanColor"]
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30,)
Dataframe shape:  (30, 785)


#### SumImg
Img (784) | Mean Color (1) | SumImg (57)

In [ ]:
SumImg = []
for img in imgs:
    SumImg.append(fe.feature_SumImg(img=img))

SumImg = np.array(SumImg)
print("Data shape: ", SumImg.shape)


temp_df = pd.DataFrame(SumImg)
print(temp_df.columns)
temp_df.columns = fng.gen_name("rowSum", 28)+fng.gen_name("colSum", 28)+["allSum"]
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30, 57)
RangeIndex(start=0, stop=57, step=1)
Dataframe shape:  (30, 842)


#### ColorHistogram
Img (784) | Mean Color (1) | SumImg (57) | ColorHistogram (256)

In [ ]:
ColorHistogram = []
for img in imgs:
    ColorHistogram.append(fe.feature_colorHistogram(img=img))

ColorHistogram = np.array(ColorHistogram)
ColorHistogram = np.squeeze(ColorHistogram)
print("Data shape: ", ColorHistogram.shape)

temp_df = pd.DataFrame(ColorHistogram)
temp_df.columns = fng.gen_name("CHistogram", 256)
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30, 256)
Dataframe shape:  (30, 1098)


#### Noise
Img (784) | Mean Color (1) | SumImg (57) | ColorHistogram (256) | feature_noise (57)

In [ ]:
noise = []
for img in imgs:
    noise.append(fe.feature_noise(img=img))

noise = np.array(noise)
print("Data shape: ", noise.shape)

temp_df = pd.DataFrame(noise)
temp_df.columns = fng.gen_name("rowNoise", 28)+fng.gen_name("colNoise", 28)+["allNoise"]
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30, 57)
Dataframe shape:  (30, 1155)


#### Gaussian Blur
Img (784) | Mean Color (1) | SumImg (57) | ColorHistogram (256) | feature_noise (57) | feature_gBlur (784)

In [ ]:
gBlur = []
for img in imgs:
    gb = fe.feature_gBlur(img=img)
    gBlur.append(fe.feature_SerializedImg(img=gb))

gBlur = np.array(gBlur)
print("Data shape: ", gBlur.shape)

temp_df = pd.DataFrame(gBlur)
temp_df.columns = fng.gen_name("gBlur", 784)
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30, 784)
Dataframe shape:  (30, 1939)


#### Gaussian Blur Mean
Img (784) | Mean Color (1) | SumImg (57) | ColorHistogram (256) | noise (57) | gBlur (784) | gBlurMean (1)

In [ ]:
gBlurMean = []
for img in imgs:
    gb = fe.feature_gBlur(img=img)
    gBlurMean.append(fe.feature_colorMean(img=gb))

gBlurMean = np.array(gBlurMean)
print("Data shape: ", gBlurMean.shape)

temp_df = pd.DataFrame(gBlurMean)
temp_df.columns = ["gBlurMean"]
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30,)
Dataframe shape:  (30, 1940)


#### Gaussian Blur Sum
Img (784) | Mean Color (1) | SumImg (57) | ColorHistogram (256) | noise (57) | gBlur (784) | gBlurMean (1) | gBlurSum (57)

In [ ]:
gBlurSum = []
for img in imgs:
    gb = fe.feature_gBlur(img=img)
    gBlurSum.append(fe.feature_SumImg(img=gb))

gBlurSum = np.array(gBlurSum)
print("Data shape: ", gBlurSum.shape)

temp_df = pd.DataFrame(gBlurSum)
temp_df.columns = fng.gen_name("rowGBlur", 28) + \
    fng.gen_name("colGBlur", 28)+["allGBlur"]
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30, 57)
Dataframe shape:  (30, 1997)


#### Median Blur
Img (784) | Mean Color (1) | SumImg (57) | ColorHistogram (256) | noise (57) | gBlur (784) | gBlurMean (1) | gBlurSum (57) | mBlur (784)

In [ ]:
mBlur = []
for img in imgs:
    mb = fe.feature_medianBlur(img=img)
    mBlur.append(fe.feature_SerializedImg(img=mb))

mBlur = np.array(mBlur)
print("Data shape: ", mBlur.shape)

temp_df = pd.DataFrame(mBlur)
temp_df.columns = fng.gen_name("mBlur", 784)
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30, 784)
Dataframe shape:  (30, 2781)


#### Median Blur Mean
Img (784) | Mean Color (1) | SumImg (57) | ColorHistogram (256) | noise (57) | gBlur (784) | gBlurMean (1) | gBlurSum (57) | mBlur (784) | mBlurMean (1)

In [ ]:
mBlurMean = []
for img in imgs:
    gb = fe.feature_medianBlur(img=img)
    mBlurMean.append(fe.feature_colorMean(img=mb))

mBlurMean = np.array(mBlurMean)
print("Data shape: ", mBlurMean.shape)

temp_df = pd.DataFrame(gBlurMean)
temp_df.columns = ["mBlurMean"]
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30,)
Dataframe shape:  (30, 2782)


#### Median Blur Sum
Img (784) | Mean Color (1) | SumImg (57) | ColorHistogram (256) | noise (57) | gBlur (784) | gBlurMean (1) | gBlurSum (57) | mBlur (784) | mBlurMean (1) | mBlurSum (57)

In [ ]:
mBlurSum = []
for img in imgs:
    mb = fe.feature_medianBlur(img=img)
    mBlurSum.append(fe.feature_SumImg(img=mb))

mBlurSum = np.array(mBlurSum)
print("Data shape: ", mBlurSum.shape)

temp_df = pd.DataFrame(mBlurSum)
temp_df.columns = fng.gen_name("rowMBlur", 28) + \
    fng.gen_name("colMBlur", 28)+["allMBlur"]
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30, 57)
Dataframe shape:  (30, 2839)


#### Canny Edge Detector
Img (784) | Mean Color (1) | SumImg (57) | ColorHistogram (256) | noise (57) | gBlur (784) | gBlurMean (1) | gBlurSum (57) | mBlur (784) | mBlurMean (1) | mBlurSum (57) | Canny (784)

In [ ]:
canny = []
for img in imgs:
    cannyDet = fe.feature_cannyEdge(img=img)
    canny.append(fe.feature_SerializedImg(img=cannyDet))

canny = np.array(canny)
print("Data shape: ", canny.shape)

temp_df = pd.DataFrame(canny)
temp_df.columns = fng.gen_name("Canny", 784)
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30, 784)
Dataframe shape:  (30, 3623)


#### Canny Edge Detector Mean
Img (784) | Mean Color (1) | SumImg (57) | ColorHistogram (256) | noise (57) | gBlur (784) | gBlurMean (1) | gBlurSum (57) | mBlur (784) | mBlurMean (1) | mBlurSum (57) | Canny (784) | CannyMean (1)

In [ ]:
cannyMean = []
for img in imgs:
    cM = fe.feature_cannyEdge(img=img)
    cannyMean.append(fe.feature_colorMean(img=cM))

cannyMean = np.array(cannyMean)
print("Data shape: ", cannyMean.shape)

temp_df = pd.DataFrame(cannyMean)
temp_df.columns = ["CannyMean"]
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30,)
Dataframe shape:  (30, 3624)


#### Canny Edge Detector Sum
Img (784) | Mean Color (1) | SumImg (57) | ColorHistogram (256) | noise (57) | gBlur (784) | gBlurMean (1) | gBlurSum (57) | mBlur (784) | mBlurMean (1) | mBlurSum (57) | Canny (784) | CannyMean (1) | CannySum (57)

In [ ]:
cannySum = []
for img in imgs:
    cS = fe.feature_cannyEdge(img=img)
    cannySum.append(fe.feature_SumImg(img=cS))

cannySum = np.array(cannySum)
print("Data shape: ", cannySum.shape)

temp_df = pd.DataFrame(cannySum)
temp_df.columns = fng.gen_name("rowCanny", 28) + \
    fng.gen_name("colCanny", 28)+["allCanny"]
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30, 57)
Dataframe shape:  (30, 3681)


## Add Label

In [ ]:
print("Data shape: ", labels.shape)
temp_df = pd.DataFrame(labels)
temp_df.columns = ["Label"]
df = pd.concat([df, temp_df], axis=1)
print("Dataframe shape: ", df.shape)


Data shape:  (30, 1)
Dataframe shape:  (30, 3682)


## Save

In [ ]:
df.to_csv('p_dataset_train.csv',index=False)